# Generated by Django 2.2.5 on 2020-04-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaejatalBaeir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baejarnafn', models.CharField(blank=True, max_length=85, null=True, verbose_name='bæjarnafn')),
                ('lbs_lykill', models.CharField(blank=True, max_length=50, null=True, verbose_name='lykill landsbókasafns')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('sveitarf_temp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'bær',
                'verbose_name_plural': 'bæir',
                'db_table': 'baejatal_baeir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaejatalSveitarfelogGomul',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skst', models.CharField(blank=True, max_length=42, null=True, verbose_name='skammstöfun')),
                ('nafn', models.CharField(blank=True, max_length=85, null=True, verbose_name='nafn')),
            ],
            options={
                'verbose_name': 'sveitarfélag (1970)',
                'verbose_name_plural': 'sveitarfélög (1970)',
                'db_table': 'baejatal_sveitarfelog_gomul',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaejatalSveitarfelogNy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skst', models.CharField(blank=True, max_length=42, null=True, verbose_name='skammstöfun')),
                ('nafn', models.CharField(blank=True, max_length=85, null=True, verbose_name='nafn')),
            ],
            options={
                'verbose_name': 'sveitarfélag',
                'verbose_name_plural': 'sveitarfélög',
                'db_table': 'baejatal_sveitarfelog_ny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaejatalSyslur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skst', models.CharField(blank=True, max_length=42, null=True, verbose_name='skammstöfun')),
                ('nafn', models.CharField(blank=True, max_length=85, null=True, verbose_name='nafn')),
            ],
            options={
                'verbose_name': 'sýsla',
                'verbose_name_plural': 'sýslur',
                'db_table': 'baejatal_syslur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Einstaklingar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafn', models.CharField(blank=True, max_length=250, null=True, verbose_name='nafn')),
                ('aukanafn', models.CharField(blank=True, max_length=250, null=True, verbose_name='aukanafn')),
                ('faedingarstadur', models.CharField(blank=True, max_length=250, null=True, verbose_name='fæðingarstaður')),
                ('heimili', models.CharField(blank=True, max_length=250, null=True, verbose_name='heimili')),
                ('faedingarar', models.IntegerField(blank=True, null=True, verbose_name='fæðingarár')),
                ('danarar', models.IntegerField(blank=True, null=True, verbose_name='dánarár')),
            ],
            options={
                'verbose_name': 'einstaklingur',
                'verbose_name_plural': 'einstaklingar',
                'db_table': 'einstaklingar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EinstaklingarBaeir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tengsl', models.CharField(blank=True, choices=[('heimili', 'Heimili'), ('fæðingarstaður', 'Fæðingarstaður')], max_length=250, null=True, verbose_name='tengsl')),
            ],
            options={
                'verbose_name': 'tengdur staður',
                'verbose_name_plural': 'tengdir staðir',
                'db_table': 'einstaklingar_baeir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ornefnaskrar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titill', models.CharField(blank=True, max_length=300, null=True)),
                ('texti', models.TextField(blank=True, null=True)),
                ('stafraent', models.BooleanField(blank=True, null=True, verbose_name='stafrænt?')),
                ('pappir', models.BooleanField(blank=True, null=True, verbose_name='pappír?')),
            ],
            options={
                'verbose_name': 'skjal',
                'verbose_name_plural': 'skjöl',
                'db_table': 'ornefnaskrar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrnefnaskrarBaeir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegund', models.CharField(blank=True, max_length=100, null=True, verbose_name='tegund')),
            ],
            options={
                'verbose_name': 'bær',
                'verbose_name_plural': 'bæir',
                'db_table': 'ornefnaskrar_baeir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrnefnaskrarEinstaklingar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlutverk', models.CharField(blank=True, choices=[('skrasetjari', 'Skrásetjari'), ('heimildamadur', 'Heimildamaður'), ('starfsmaður örnefnastofnunar', 'Starfsmaður Örnefnastofnunar'), ('kortagerð', 'Kortagerð')], max_length=200, null=True, verbose_name='hlutverk')),
            ],
            options={
                'verbose_name': 'einstaklingur',
                'verbose_name_plural': 'einstaklingar',
                'db_table': 'ornefnaskrar_einstaklingar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrnefnaskrarOrnefni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'örnefni',
                'verbose_name_plural': 'örnefni',
                'db_table': 'ornefnaskrar_ornefni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrnefnaskrarStada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athugasemd', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'staða skjals',
                'verbose_name_plural': 'staða skjals',
                'db_table': 'ornefnaskrar_stada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrnefnaskrarTegundir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'tegund skjals',
                'verbose_name_plural': 'tegund skjals',
                'db_table': 'ornefnaskrar_tegundir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ornefni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ornefni', models.CharField(blank=True, max_length=300, null=True, verbose_name='örnefni')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'örnefni',
                'verbose_name_plural': 'örnefni',
                'db_table': 'ornefni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdfSkrarFinnur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysla_id', models.IntegerField(blank=True, null=True, verbose_name='auðkenni sýslu')),
                ('hreppur_id', models.IntegerField(blank=True, null=True, verbose_name='auðkenni hrepps')),
                ('sysla', models.CharField(blank=True, max_length=300, null=True, verbose_name='sýsla (samkvæmt Finni)')),
                ('hreppur', models.CharField(blank=True, max_length=300, null=True, verbose_name='hreppur (samkvæmt Finni)')),
                ('slod', models.FileField(max_length=500, upload_to='nyskannad/', verbose_name='pdf skrá')),
                ('ocr_text', models.TextField(blank=True, null=True, verbose_name='ljóslesinn texti')),
            ],
            options={
                'verbose_name': 'pdf skrá',
                'verbose_name_plural': 'pdf skrár',
                'db_table': 'pdf_skrar_finnur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stada', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'stada',
                'verbose_name_plural': 'stöður',
                'db_table': 'stada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tegundir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegund', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'tegund',
                'verbose_name_plural': 'tegundir',
                'db_table': 'tegundir',
                'managed': False,
            },
        ),
    ]
