# Generated by Django 2.2.5 on 2020-08-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafnid_django_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaejatalBaeirHreppar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'baejatal_baeir_sveitarfelog_gomul',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaejatalBaeirSveitarfelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'baejatal_baeir_sveitarfelog_ny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaejatalSveitarfelogGomulSyslur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'baejatal_sveitarfelog_gomul_syslur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaejatalSveitarfelogNySyslur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'baejatal_sveitarfelog_ny_syslur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OCROrnefni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ornefni', models.CharField(blank=True, max_length=300, null=True, verbose_name='örnefni')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('okay', models.BooleanField(blank=True, null=True, verbose_name='Rétt')),
            ],
            options={
                'verbose_name': 'Ljóslesið örnefni',
                'verbose_name_plural': 'Ljóslesin örnefni',
                'db_table': 'ocr_ornefni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ornefnapakki',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ornefni', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ornefnapakki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrnefnaskrarOCROrnefni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'örnefni',
                'verbose_name_plural': 'örnefni',
                'db_table': 'ornefnaskrar_ocrornefni',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ornefnaskrareinstaklingar',
            options={'managed': False, 'verbose_name': 'örnefnaskrá', 'verbose_name_plural': 'örnefnaskrár'},
        ),
    ]
