# Generated by Django 2.2.5 on 2020-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafnid_django_admin', '0002_auto_20200831_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='EinstaklingarOrnefnaskrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlutverk', models.CharField(blank=True, choices=[('skrasetjari', 'Skrásetjari'), ('heimildamadur', 'Heimildamaður'), ('starfsmadur', 'Starfsmaður Örnefnastofnunar'), ('kortagerð', 'Kortagerð')], max_length=200, null=True, verbose_name='hlutverk')),
            ],
            options={
                'verbose_name': 'örnefnaskrá',
                'verbose_name_plural': 'örnefnaskrár',
                'db_table': 'ornefnaskrar_einstaklingar',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ornefnaskrareinstaklingar',
            options={'managed': False, 'verbose_name': 'einstaklingur', 'verbose_name_plural': 'einstaklingar'},
        ),
    ]
