# Generated by Django 3.1.7 on 2021-11-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafnid_django_admin', '0003_auto_20200901_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abendingar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafn', models.CharField(max_length=250, verbose_name='nafn sendanda')),
                ('netfang', models.CharField(max_length=250, verbose_name='netfang sendanda')),
                ('simanumer', models.CharField(blank=True, max_length=50, null=True, verbose_name='símanúmer sendanda')),
                ('skilabod', models.TextField(blank=True, null=True, verbose_name='skilaboð')),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='tegund gagns')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='auðkennisnúmer gagns')),
                ('entity_name', models.TextField(blank=True, null=True, verbose_name='heiti gagns')),
                ('inserttime', models.DateTimeField(auto_now_add=True, verbose_name='dagsetning')),
            ],
            options={
                'verbose_name': 'ábending notanda',
                'verbose_name_plural': 'ábendingar notenda',
                'db_table': 'abendingar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaeirOrnefnaskrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegund', models.CharField(blank=True, max_length=100, null=True, verbose_name='tegund')),
            ],
            options={
                'verbose_name': 'örnefnaskra',
                'verbose_name_plural': 'örnefnaskrar',
                'db_table': 'ornefnaskrar_baeir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaejatalTegund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegund', models.CharField(max_length=300, verbose_name='tegund')),
            ],
            options={
                'verbose_name': 'tegund svæðis',
                'verbose_name_plural': 'tegundir svæða',
                'db_table': 'baejatal_tegund',
                'ordering': ['tegund'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Frumskraning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fjoldi_skjala', models.IntegerField(blank=True, null=True, verbose_name='fjöldi skjala')),
                ('athugasemd', models.TextField(blank=True, null=True, verbose_name='athugasemd')),
                ('dagsetning_fra', models.CharField(blank=True, help_text='yyyy-mm-dd', max_length=100, null=True, verbose_name='dagsetning frá')),
                ('dagsetning_til', models.CharField(blank=True, help_text='yyyy-mm-dd', max_length=100, null=True, verbose_name='dagsetning til')),
            ],
            options={
                'verbose_name': 'frumskráning',
                'verbose_name_plural': 'frumskráningar',
                'db_table': 'frumskraning',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hlutverk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlutverk', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'hlutverk',
                'verbose_name_plural': 'hlutverk',
                'db_table': 'hlutverk',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OCROrnefni',
        ),
        migrations.DeleteModel(
            name='OrnefnaskrarOCROrnefni',
        ),
        migrations.AlterModelOptions(
            name='baejatalbaeir',
            options={'managed': False, 'verbose_name': 'svæði', 'verbose_name_plural': 'svæði'},
        ),
        migrations.AlterModelOptions(
            name='baejatalsveitarfeloggomul',
            options={'managed': False, 'ordering': ('nafn',), 'verbose_name': 'sveitarfélag (1970)', 'verbose_name_plural': 'sveitarfélög (1970)'},
        ),
        migrations.AlterModelOptions(
            name='baejatalsveitarfelogny',
            options={'managed': False, 'ordering': ('nafn',), 'verbose_name': 'sveitarfélag', 'verbose_name_plural': 'sveitarfélög'},
        ),
        migrations.AlterModelOptions(
            name='ornefni',
            options={'managed': False, 'ordering': ('ornefni',), 'verbose_name': 'Ljóslesið örnefni', 'verbose_name_plural': 'Ljóslesin örnefni'},
        ),
        migrations.AlterModelTable(
            name='ornefnaskrarornefni',
            table='ornefnaskrar_ocrornefni',
        ),
        migrations.AlterModelTable(
            name='ornefni',
            table='ocr_ornefni',
        ),
    ]
