# Generated by Django 5.0.3 on 2025-05-05 09:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafnid_django_admin', '0004_auto_20211129_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'greinasafn',
                'verbose_name_plural': 'greinasöfn',
                'db_table': 'article_collections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='titill')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='innihald')),
            ],
            options={
                'verbose_name': 'grein',
                'verbose_name_plural': 'greinar',
                'db_table': 'articles',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlesAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'höfundur greinar',
                'verbose_name_plural': 'höfundar greina',
                'db_table': 'articles_authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlesBaeir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'tengdur bær',
                'verbose_name_plural': 'tengdir bæir',
                'db_table': 'articles_baeir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrumskraningarBaeir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'tengdur bær/svæði',
                'verbose_name_plural': 'aðrir tengir bæir/svæði',
                'db_table': 'frumskraningar_baer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geoleit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('baer_id', models.IntegerField(blank=True, null=True)),
                ('baer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ornefnaskra', models.IntegerField(blank=True, null=True)),
                ('hreppur_id', models.IntegerField(blank=True, null=True)),
                ('hreppur', models.CharField(blank=True, max_length=255, null=True)),
                ('sysla_id', models.IntegerField(blank=True, null=True)),
                ('sysla', models.CharField(blank=True, max_length=255, null=True)),
                ('tegund', models.CharField(blank=True, max_length=255, null=True)),
                ('tegund_id', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('article_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geoleit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grunngogn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athugasemd', models.TextField(blank=True, null=True)),
                ('dagsetning_fra', models.CharField(blank=True, max_length=100, null=True)),
                ('dagsetning_til', models.CharField(blank=True, max_length=100, null=True)),
                ('myndagogn', models.BooleanField(default=False, verbose_name='myndagögn?')),
            ],
            options={
                'db_table': 'grunngogn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrunngognBaer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'grunngogn_baer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrnefnaskrarOrnefnapakki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skra_texti', models.TextField()),
            ],
            options={
                'verbose_name': 'örnefni',
                'verbose_name_plural': 'örnefni',
                'db_table': 'ornefnaskrar_ocrornefni',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ornefnaskrarbaeir',
            options={'managed': False, 'verbose_name': 'svæði', 'verbose_name_plural': 'svæði'},
        ),
    ]
