# Generated by Django 5.0.3 on 2025-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafnid_django_admin', '0005_articlecollections_articles_articlesauthors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NofnIslendingaGreinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texti', models.TextField(verbose_name='texti')),
                ('heimild', models.TextField()),
                ('ath1', models.TextField()),
                ('ath2', models.TextField()),
                ('nafn', models.CharField(max_length=255, verbose_name='uppflettinafn')),
                ('visun', models.CharField(max_length=255, verbose_name='vísun')),
            ],
            options={
                'verbose_name': 'Nöfn íslendinga: greinar',
                'verbose_name_plural': 'tengdir bæir',
                'db_table': 'nofn_islendinga_greinar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NofnIslendingaGreinNofn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grein', models.CharField(max_length=255, verbose_name='uppflettinafn')),
                ('nafn', models.CharField(max_length=255, verbose_name='uppflettinafn')),
            ],
            options={
                'verbose_name': 'Nöfn íslendinga: greinar við nöfn',
                'verbose_name_plural': 'tengdir bæir',
                'db_table': 'nofn_islendinga_greinar_nofn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NofnIslendingaNofn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafn', models.CharField(max_length=255, verbose_name='uppflettinafn')),
                ('ofl', models.CharField(blank=True, max_length=20, null=True, verbose_name='kyn')),
                ('beyging', models.CharField(blank=True, max_length=255, null=True, verbose_name='beying')),
            ],
            options={
                'verbose_name': 'Nöfn íslendinga',
                'verbose_name_plural': 'tengdir bæir',
                'db_table': 'nofn_islendinga_nofn',
                'managed': False,
            },
        ),
    ]
