"""
Django settings for nafnid_django project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from . import dbconfig;

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'enp9j&-1=wxetwp3(oh&y(%_34&s2qwl5+uik0crdbi%47s9av'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '130.208.108.18', 'nidhoggur.rhi.hi.is', 'nafnid.arnastofnun.is', 'nafnid.is', 'xn--nafni-mta.is']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nafnid_django_admin',
    'django_admin_listfilter_dropdown',
    'rest_framework',
    'vefur_django_admin',
    'ckeditor',
    'ckeditor_uploader',
    'vefur_rest_api',
    'rest_framework_recaptcha',
    #'api',
	#'debug_toolbar'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
	#'debug_toolbar.middleware.DebugToolbarMiddleware'
]

ROOT_URLCONF = 'nafnid_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nafnid_django.wsgi.application'
DATA_UPLOAD_MAX_NUMBER_FIELDS = None


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': dbconfig.config
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/django-static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media//uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/uploads/')

CORS_ORIGIN_ALLOW_ALL = True

# Recaptcha key
DRF_RECAPTCHA_SECRET_KEY = '6LfSlPcZAAAAALuhTE23zeqAkgfoJrto4KF6k1BY'


CKEDITOR_BASEPATH = '/django-static/ckeditor/ckeditor/'
CKEDITOR_UPLOAD_PATH = 'uploads/'

CKEDITOR_CONFIGS = {
    'default': {
        'basicEntities': True,
        'entities': False,
        'allowedContent': True,
        'fillEmptyBlocks': False,
        'autoParagraph': False,
        'removePlugins': 'htmldataprocessor, stylescombo',
        'protectedSource': [],
        'contentsCss': 'http://blondal.arnastofnun.is/css/text-styles.css'
    }
}


# Pagination

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50
}

INTERNAL_IPS = [
	'130.208.108.18',
	'85.220.46.164'
]