# Generated by Django 2.2.5 on 2020-04-14 14:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forsiduhlutar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafn', models.CharField(blank=True, max_length=250, null=True, verbose_name='nafn')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='innihald')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='röðun')),
                ('css_class', models.CharField(blank=True, max_length=250, null=True, verbose_name='css klassi')),
            ],
            options={
                'verbose_name': 'forsíðuhlutar',
                'verbose_name_plural': 'forsíðuhluti',
                'db_table': 'vefur_forsiduhlutar',
                'ordering': ['order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200, verbose_name='titill')),
                ('url', models.CharField(default='', max_length=100, verbose_name='slóð')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='innihald')),
                ('in_menu', models.BooleanField(default=False, verbose_name='birta í valmynd')),
                ('menu_separator', models.BooleanField(default=False, verbose_name='skipting valmyndar')),
                ('use_as_link', models.BooleanField(default=False, verbose_name='tengill')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='röðun')),
            ],
            options={
                'verbose_name': 'síða',
                'verbose_name_plural': 'síður',
                'db_table': 'vefur_pages',
                'ordering': ['order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='heiti')),
            ],
            options={
                'verbose_name': 'Síðuhluti',
                'verbose_name_plural': 'Síðuhlutar',
                'db_table': 'vefur_pages_sites',
                'managed': False,
            },
        ),
    ]
